server:
  schema: http
  domain:
  port: 8888
  context-path: /hiynn-cas-client
  https:
    port: 9997
    keyStorePath: D:/hiynn.keystore
    keyStorePassword: 123456
  description: cas-permissionIds-client
  service:
    #cas-permissionIds-server部署地址 + /remoteService
    remoteServerServiceUrl: http://192.168.3.20:8080/hiynn-cas-server/remoteServerService
    #需要在每一个系统里的配置文件中覆盖掉该配置，每一个系统的appKey都不一样
    # TODO 考虑提供一个可以自动生成appKey的接口
    appKey: cas-client

shiro:
  #关闭shiro注解，当和spring整合的时候，如果使用了@Transactional的时候会应为AOP代理的问题而造成启动失败。即使设置使用CGLIB也不行
  # TODO 待研究
  annotations:
    enabled: false
  cas:
    schema: http
    domain: 192.168.3.20
    port: 8080
    context-path: /cas
    casServerUrlPrefix: ${shiro.cas.schema}://${shiro.cas.domain}:${shiro.cas.port}${shiro.cas.context-path}
    casServerLoginUrl: ${shiro.cas.casServerUrlPrefix}/login
    callbackUrlSuffix: /callback
    callbackUrl: ${server.schema}://${server.domain}:${server.port}${server.context-path}${shiro.cas.callbackUrlSuffix}
    #callbackUrl在身份验证完毕以后要跳转回原始请求页面（OriginallyRequestedUrl，保存到session中）
    #如果因未知因素导致未从session中拿到OriginallyRequestedUrl，则会跳转到defaultUrl，其值默认为“/”
    callbackFilterDefaultUrl: ${server.schema}://${server.domain}:${server.port}${server.context-path}/service/hello
    logoutFilterDefaultUrl: ${server.schema}://${server.domain}:${server.port}${server.context-path}/ajaxlogout

  #为ShiroFilterFactoryBean设置loginUrl属性{@link AbstractShiroWebFilterConfiguration#loginUrl}
  loginUrl: ${shiro.cas.casServerLoginUrl}?service=${shiro.cas.callbackUrl}
  successUrl: /
  #本地权限配置，默认提供的只有与CAS单点登录相关的权限设置，其中/**=securityFilter可根据实际需求进行更改，建议依赖该模块的项目重写该配置
  filterChainDefinitions: |
    /logout=logout
    /callback=cas
    /**=securityFilter
  #是否从数据库加载动态权限
  loadDBPermissionsEnabled: false
  #当远程权限系统Server不可用是，是否允许忽略动态权限加载，默认不允许（false）。
  #注意，如果设置为true，在远程Server不可用时，数据库中配置的应用权限将被忽略，可能对系统造成不可恢复的损坏
  ignoreDBPermissionsEnabled: false
