server:
  schema: http
  context-path: /hiynn-cas-client
  port: 8888
  https:
    port: 9997
    keyStorePath: D:/hiynn.keystore
    keyStorePassword: 123456
  description: cas-permissions-client
  service:
    #cas-permissions-server部署地址 + /remoteService
    remoteServiceUrl: http://192.168.3.20:8080/hiynn-cas-server/remoteService
    #需要在每一个系统里的配置文件中覆盖掉该配置，每一个系统的appKey都不一样
    # TODO 考虑提供一个可以自动生成appKey的接口
    appKey: cas-client

shiro:
  cas:
    schema: http
    domain: 192.168.3.20
    port: 8080
    context-path: /cas
    casServerUrlPrefix: ${shiro.cas.schema}://${shiro.cas.domain}:${shiro.cas.port}${shiro.cas.context-path}
    casServerLoginUrl: ${shiro.cas.casServerUrlPrefix}/login
    callbackUrlSuffix: /callback
    callbackUrl: ${server.schema}://${shiro.cas.domain}:${server.port}${server.context-path}${shiro.cas.callbackUrlSuffix}
    #callbackUrl在身份验证完毕以后要跳转回原始请求页面（OriginallyRequestedUrl，保存到session中）
    #如果因未知因素导致未从session中拿到OriginallyRequestedUrl，则会跳转到defaultUrl，其值默认为“/”
    callbackFilterDefaultUrl: ${server.schema}://${shiro.cas.domain}:${server.port}${server.context-path}/service/hello
    logoutFilterDefaultUrl: ${server.schema}://${shiro.cas.domain}:${server.port}${server.context-path}/ajaxlogout

  #为ShiroFilterFactoryBean设置loginUrl属性{@link AbstractShiroWebFilterConfiguration#loginUrl}
  loginUrl: ${shiro.cas.casServerLoginUrl}?service=${shiro.cas.callbackUrl}
  successUrl: /

