server:
  context-path: /hiynn-cas
  port: 8080
  https:
    port: 9443
    keyStorePath: D:/hiynn.keystore
    keyStorePassword: 123456
  testHelloMessage: server1

shiro:
  cas:
    domain: www.casserver.com
    casServerUrlPrefix: https://${shiro.cas.domain}:8443/cas
    casServerLoginUrl: ${shiro.cas.casServerUrlPrefix}/login
    #casService: https://{domain}:{server https port if https is enable OR http port}/{projectName}/{filter path mapping}
    #context-path中已经添加了“/”
    callbackUrl: http://${shiro.cas.domain}:${server.port}${server.context-path}/callback
    #callbackUrl在身份验证完毕以后要跳转回原始请求页面（OriginallyRequestedUrl，保存到session中），
    #如果因未知因素导致未从session中拿到OriginallyRequestedUrl，则会跳转到defaultUrl，其值默认为“/”
    callbackFilterDefaultUrl: http://${shiro.cas.domain}:${server.port}${server.context-path}/service/hello
    logoutFilterDefaultUrl: http://${shiro.cas.domain}:${server.port}${server.context-path}/ajaxlogout

  #为ShiroFilterFactoryBean设置loginUrl属性{@link AbstractShiroWebFilterConfiguration#loginUrl}
  loginUrl: ${shiro.cas.casServerLoginUrl}?service=${shiro.cas.callbackUrl}
  successUrl: /
