shiro:
  cas:
    casServerUrlPrefix: https://www.casserver.com:8443/cas
    casServerLoginUrl: ${shiro.cas.casServerUrlPrefix}/login
    #casService: https://{domain}:{server https port if https is enable OR http port}/{projectName}/{filter path mapping}
    #?client_name=${shiro.cas.casClientName}
    casService: https://www.casserver.com:9443/hiynn-cas/callback
    casClientName: client1
  #为ShiroFilterFactoryBean设置loginUrl属性{@link AbstractShiroWebFilterConfiguration#loginUrl}
  loginUrl: ${shiro.cas.casServerLoginUrl}?service=${shiro.cas.casService}
  successUrl: /

server:
  context-path: /hiynn-cas

